### ISSUE TITLE
Cascading doesn't update and needs clicking multiple times

### ISSUE THREAD

**Issue by Azgorn** [pbogre/minesweeper-CBL#21]
The method `cascade` should reveal every zero until all of the borders of the revealed shape are non-zero; The method works but not from a **single click** , it takes multiple clicks for **everything** to be revealed. Regardless it is inefficient and needs refactoring/fixing

**Comment by pbogre** [comment]
@Azgorn  is this issue still a thing? close if not

**Comment by Azgorn** [comment]
the issue is closed in the pull request we're reviewing now

**Comment by pbogre** [comment]
> the issue is closed in the pull request we're reviewing now

issues are independent of branches, and this issue was both introduced and fixed in that pull request (there is no "cascading" in `base-game` or `main`)

**Comment by Azgorn** [comment]
cascading is the same as revealNeighborCells, i'll just close it when we merge

**Comment by pbogre** [comment]
i meant the concept of cascading, there can't be a problem with cascading if we haven't implemented it yet in one of the main branches

**Comment by Azgorn** [comment]
do you propose to just deleted the issue?

**Comment by pbogre** [comment]
no i was just saying for future issues, dont worry
